FROM python:latest

WORKDIR usr/src/app

COPY classes_and_files telegramdumpfinder/classes_and_files
COPY main.py telegramdumpfinder
COPY create_session.py telegramdumpfinder

RUN pip install --upgrade pip
RUN pip install telethon
RUN pip install paho.mqtt
